/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-fixed-dim": "#7bd0ff",
              "primary-container": "#0f172a",
              "primary": "#bec6e0",
              "on-background": "#d4e4fa",
              "on-secondary-fixed": "#001e2c",
              "inverse-primary": "#565e74",
              "tertiary-fixed-dim": "#4ae176",
              "secondary-container": "#00a6e0",
              "warning-amber": "#F59E0B",
              "error": "#ffb4ab",
              "on-primary": "#283044",
              "tertiary": "#4ae176",
              "inverse-on-surface": "#233143",
              "primary-fixed-dim": "#bec6e0",
              "outline": "#909097",
              "surface-dim": "#051424",
              "border-subtle": "#1E293B",
              "inverse-surface": "#d4e4fa",
              "alert-red": "#EF4444",
              "on-secondary": "#00354a",
              "on-tertiary-fixed": "#002109",
              "on-secondary-fixed-variant": "#004c69",
              "on-error-container": "#ffdad6",
              "secondary-fixed": "#c4e7ff",
              "on-secondary-container": "#00374d",
              "surface-bright": "#2c3a4c",
              "on-surface": "#d4e4fa",
              "tertiary-container": "#001d07",
              "secondary": "#7bd0ff",
              "surface-container-low": "#0d1c2d",
              "error-container": "#93000a",
              "surface-container-high": "#1c2b3c",
              "surface-container-highest": "#273647",
              "outline-variant": "#45464d",
              "on-primary-fixed-variant": "#3f465c",
              "background": "#051424",
              "on-tertiary": "#003915",
              "bg-deep": "#020617",
              "surface-variant": "#273647",
              "surface-container": "#122131",
              "surface-tint": "#bec6e0",
              "on-tertiary-fixed-variant": "#005321",
              "primary-fixed": "#dae2fd",
              "on-surface-variant": "#c6c6cd",
              "on-primary-container": "#798098",
              "tertiary-fixed": "#6bff8f",
              "surface-container-lowest": "#010f1f",
              "on-error": "#690005",
              "surface": "#051424",
              "on-primary-fixed": "#131b2e",
              "on-tertiary-container": "#009542"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "margin": "24px",
              "unit": "4px",
              "container-max": "1280px",
              "gutter": "16px"
      },
      "fontFamily": {
              "code-md": ["JetBrains Mono"],
              "label-caps": ["JetBrains Mono"],
              "headline-md": ["Inter"],
              "headline-sm": ["Inter"],
              "body-md": ["Inter"],
              "headline-lg": ["Inter"],
              "code-sm": ["JetBrains Mono"],
              "body-lg": ["Inter"]
      },
    },
  },
  plugins: [],
}
